theme: jekyll-theme-minimal
title: 3h4
description: a blog by @electric-blue-green Raspberry Pi | Arduino | Photography | Music | Theatre
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      
docs_list_title: Pages
docs:
- title: About
  url: index.md

- title: Configuration
  url: configuration.html

- title: Deployment
  url: deployment.html
